### ISSUE TITLE
请问如何获得抖音直播间的 礼物信息 

### ISSUE THREAD

**Issue by a576435459** [XiaoXinYo/Tiktok_Barrage#14]
请问如何获得抖音直播间的 礼物信息

**Comment by ykaiqx** [comment]
目前还不支持获取礼物，以后将会支持

------------------ 原始邮件 ------------------
发件人: a576435459 ***@***.***&gt;
发送时间: 2023年2月25日 15:34
收件人: XiaoXinYo/Live-Barrage ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[XiaoXinYo/Live-Barrage] 请问如何获得抖音直播间的 礼物信息  (Issue #14)





 
请问如何获得抖音直播间的 礼物信息
