### ISSUE TITLE
请问有办法获取抖音 app 的数据吗？

### ISSUE THREAD

**Issue by SuperRay3** [XiaoXinYo/Tiktok_Barrage#15]
例如抖音搜索页。

**Comment by ykaiqx** [comment]
无，此仓库的弹幕获取用的是dom解析法
------------------ 原始邮件 ------------------
发件人: 雷雷雷_Ray ***@***.***&gt;
发送时间: 2023年2月28日 08:28
收件人: XiaoXinYo/Live-Barrage ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[XiaoXinYo/Live-Barrage] 请问有办法获取抖音 app 的数据吗？ (Issue #15)





 
例如抖音搜索页。
