### ISSUE TITLE
想问下能加入礼物的解析嘛？

### ISSUE THREAD

**Issue by Nkomol** [XiaoXinYo/Tiktok_Barrage#17]
请问下大佬可以加入礼物的解析嘛？
快手的id是怎么获取的呢？

**Comment by Nkomol** [comment]
刚刚看了下bilibii的只有首次会发送一个系统消息，后面的好像都不会发送，只有弹幕的消息，这是b站网页端的问题嘛

**Comment by ykaiqx** [comment]
礼物解析暂时不考虑，bug马上修复

**Comment by ykaiqx** [comment]
查看页面源代码,搜索liveStream后面ID的值即直播流ID

**Comment by ykaiqx** [comment]
我刚刚试了一下哔哩哔哩的没问题啊，
<img width="334" alt="WechatIMG414" src="https://user-images.githubusercontent.com/56395004/235473825-febe63f0-8295-42f8-8bfe-ae1fb5fe6fe6.png">

**Comment by Nkomol** [comment]
我刚刚看了下哔哩哔哩chat-items现在除了自己进去会有，其他的进入都没显示在这个列表里面了，也有可能是系统的消息确实没有多少

**Comment by ykaiqx** [comment]
可以直播网址发过来看看吗

**Comment by Nkomol** [comment]
![image](https://user-images.githubusercontent.com/40691277/235582979-9e1ca8ac-9721-4d13-9cfb-d13133cb3ce1.png)
https://live.bilibili.com/?spm_id_from=333.1007.0.0 地址在这里，他好像是显示在这个位置，推送过几秒就下一个或者有新的1秒后就下一条了，进入直播间信息好像不会显示在弹幕那个框里面了

**Comment by ykaiqx** [comment]
我已更新哔哩哔哩的js你试试

**Comment by Nkomol** [comment]
![image](https://user-images.githubusercontent.com/40691277/235630248-5ca1a947-7753-4c9a-8c16-87ce31c1618f.png)
1.我开了一个大直播间，现在投喂会显示到弹幕列表中，如果可以的话最好可以是将投喂的名称是什么可以传回来


2.再解析回数据的时候之前有报错，好像是因为没值的原因
        for data_count in data:
            if data_count.get('type') is not None and data_count.get('nickname') is not None and data_count.get('content') is not None:
                print('{:10s} | {:10s} | {:10s}'.format(data_count.get('type'), data_count.get('nickname'), data_count.get('content')))
我将输出的代码加了下

**Comment by ykaiqx** [comment]
这个投喂是文本，还是啥？

**Comment by Nkomol** [comment]
投喂的是礼物，
![image](https://user-images.githubusercontent.com/40691277/235634001-154cbb53-56c9-41f3-8020-bf9a58a29bf2.png)
https://live.bilibili.com/5555 例如这个直播间

**Comment by ykaiqx** [comment]
并不打算支持礼物

**Comment by Nkomol** [comment]
好的，那建议将礼物投喂的可以剔除一下，又发现一个问题，如果前面带粉丝牌的话，则没法判断是昵称还是牌子
如图：
![image](https://user-images.githubusercontent.com/40691277/235693970-08accc5f-f2e6-406d-9630-c2b9dda8623d.png)

**Comment by ykaiqx** [comment]
更新了，试试
