### ISSUE TITLE
开发者你好，请问抖音的运行示例能详细一点吗

### ISSUE THREAD

**Issue by saberc8** [XiaoXinYo/Tiktok_Barrage#9]

**Comment by ykaiqx** [comment]
1. 首先你需要运行TikTok/example目录下的barrage.py文件（搭建WebSocket服务器），你如果熟悉其他语言的话，可以自己写。
2. 在浏览器控制台上运行barrage.js文件（将文件中的代码粘贴到控制台执行就行了），注意修改你的websocket连接地址。
3. 随后你便可以在websocket服务器上看到弹幕消息。

**Comment by saberc8** [comment]
谢谢 我试试
